server:
  port: ${port:8080}

spring:
  application:
    name: hello
  cloud:
    consul:
      host: localhost
      port: 8500

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: true
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false