server:
  port: ${port:7070}

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500

ribbon:
  ServerListRefreshInterval: 1

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false

zuul:
  routes:
    hello:
      path: /hello/**
      serviceId: hello

