server:
  port: ${port:8091}

spring:
  application:
    name: gateway-client
  cloud:
    consul:
      host: localhost
      port: 8500

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false