server:
  port: ${port:8090}

spring:
  application:
    name: client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    enabled: true
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false