server:
  port: ${PORT:8090}

spring:
  application:
    name: client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

ribbon:
  ServerListRefreshInterval: 1
  retryableStatusCodes: 500
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ReadTimeout: 10000
  ConnectTimeout: 10000
  EnablePrimeConnections: true
  eureka.enabled: false

endpoints:
  health:
    enabled: true
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000